nama_mhs = input("Masukkan nama anda : ")
nim = input("Masukkan nim anda : ")
umur = input("Masukkan umur anda : ")
motivasi = input("Masukkan motivasi anda mengambil Prodi Teknik Informatika : ")
print("========================================================================")
print("Nama Anda : ",nama_mhs)
print("NIM Anda : ",nim)
print("Umur Anda : ",umur, " tahun")
print("Motivasi anda mengambil prodi teknik informatika : ",motivasi)

